# Generated by Django 5.2.12 on 2026-03-16 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='google_picture_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
