# Generated by Django 5.2.12 on 2026-03-12 04:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0002_roomparticipant_last_ping_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChessMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('in_progress', 'In Progress'), ('finished', 'Finished')], default='waiting', max_length=20)),
                ('result', models.CharField(choices=[('1-0', 'White Win'), ('0-1', 'Black Win'), ('1/2-1/2', 'Draw'), ('*', 'Pending')], default='*', max_length=10)),
                ('result_type', models.CharField(blank=True, choices=[('checkmate', 'Checkmate'), ('stalemate', 'Stalemate'), ('resignation', 'Resignation'), ('draw_agreed', 'Draw Agreed'), ('insufficient_material', 'Insufficient Material'), ('fifty_move_rule', 'Fifty Move Rule'), ('threefold_repetition', 'Threefold Repetition')], max_length=30, null=True)),
                ('initial_fen', models.TextField(default='rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1')),
                ('current_fen', models.TextField(default='rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1')),
                ('pgn', models.TextField(blank=True, default='')),
                ('halfmove_clock', models.PositiveIntegerField(default=0)),
                ('fullmove_number', models.PositiveIntegerField(default=1)),
                ('is_check', models.BooleanField(default=False)),
                ('is_checkmate', models.BooleanField(default=False)),
                ('is_stalemate', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('black_player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_as_black', to=settings.AUTH_USER_MODEL)),
                ('draw_offered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='draw_offers_made', to=settings.AUTH_USER_MODEL)),
                ('room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='match', to='rooms.gameroom')),
                ('white_player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_as_white', to=settings.AUTH_USER_MODEL)),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_won', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChessMove',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('move_number', models.PositiveIntegerField()),
                ('side', models.CharField(choices=[('white', 'White'), ('black', 'Black')], max_length=10)),
                ('from_square', models.CharField(max_length=2)),
                ('to_square', models.CharField(max_length=2)),
                ('uci', models.CharField(max_length=10)),
                ('san', models.CharField(max_length=20)),
                ('promotion_piece', models.CharField(blank=True, default='', max_length=10)),
                ('fen_after', models.TextField()),
                ('is_capture', models.BooleanField(default=False)),
                ('is_check', models.BooleanField(default=False)),
                ('is_checkmate', models.BooleanField(default=False)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moves', to='chessplay.chessmatch')),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chess_moves', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['move_number', 'created_at'],
                'unique_together': {('match', 'move_number')},
            },
        ),
    ]
