# Generated by Django 6.0.3 on 2026-03-11 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomparticipant',
            name='last_ping_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
